# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Tunneling Numerical Tours with FEniCSx
author: YC

repository:
  url: https://github.com/clementyvan/Tunnels_with_fenics  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# html:  
#   extra_footer: |
#     <div>
#         This webpage is an adaptation of <a href=https://comet-fenics.readthedocs.io>The COMET tutorial</a> and
#         is distributed under the terms of the <a href=http://creativecommons.org/licenses/by-sa/4.0/>Creative Commons Attribution-ShareAlike 4.0 International License  </a>
#         which permits use, duplication, adaptation, distribution and reproduction in any medium or format, as long as you give appropriate credit to the original author(s) and the source,
#         provide a link to the Creative Commons license and indicate if changes were made.  If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original. 
#     </div>

exclude_patterns: [
    ...,
    "**/*.ipynb",
    "**/*.py",
    README.md]

# Sphinx configuration for custom theme
sphinx:
  config:
    bibtex_reference_style: author_year
    html_theme: sphinx_book_theme
    html_show_copyright: false
    html_static_path: ["_static"]
    html_css_files: ["custom.css"]
    html_theme_options:
      pygment_light_style: "friendly"
      show_navbar_depth: 1
      home_page_in_toc: true
      show_toc_level: 2
      repository_url: https://github.com/clementyvan/Tunnels_with_fenics
      use_edit_page_button: true
      use_repository_button: true
      use_download_button: false
    
parse:
  myst_enable_extensions:
    - "amsmath"
    - "colon_fence"
    - "deflist"
    - "dollarmath"
    - "html_admonition"
    - "html_image"
    - "linkify"
    - "replacements"
    - "smartquotes"
    - "substitution"
    - "attrs_inline"
